# 擴展保險新聞關鍵字配置 - 專業加強版
# Expanded Insurance News Keywords Configuration

# 核心保險關鍵字
core_insurance:
  - "保險"
  - "保單"
  - "保費"
  - "保額"
  - "理賠"
  - "投保"
  - "續保"
  - "退保"

# 保險類型 - 大幅擴展
insurance_types:
  basic:
    - "壽險"
    - "產險"
    - "車險"
    - "健康險"
    - "意外險"
    - "旅平險"
    - "醫療險"
    - "癌症險"
    - "失能險"
    - "年金險"
  advanced:
    - "投資型保單"
    - "外幣保單"
    - "變額壽險"
    - "變額年金"
    - "萬能壽險"
    - "定期壽險"
    - "終身壽險"
    - "儲蓄險"
    - "養老險"
    - "教育金保險"
  specialty:
    - "長照險"
    - "長期照護險"
    - "殘扶險"
    - "失智險"
    - "重大疾病險"
    - "重大傷病險"
    - "特定疾病險"
    - "住院醫療險"
    - "手術險"
    - "實支實付"
  property:
    - "火險"
    - "地震險"
    - "颱風險"
    - "水災險"
    - "住宅險"
    - "家財險"
    - "公共意外責任險"
    - "職業災害險"
    - "雇主責任險"
    - "專業責任險"
  commercial:
    - "企業保險"
    - "團體保險"
    - "員工福利"
    - "董監事責任險"
    - "產品責任險"
    - "網路資安險"
    - "營業中斷險"
    - "信用保險"
    - "保證保險"
    - "出口信用險"

# 保險公司 - 完整覆蓋
insurance_companies:
  life_insurance:
    - "國泰人壽"
    - "富邦人壽"
    - "新光人壽"
    - "南山人壽"
    - "中國人壽"
    - "台灣人壽"
    - "全球人壽"
    - "三商美邦"
    - "宏泰人壽"
    - "遠雄人壽"
    - "安聯人壽"
    - "保德信人壽"
    - "友邦人壽"
    - "台銀人壽"
    - "第一金人壽"
    - "元大人壽"
    - "中華郵政"
    - "合庫人壽"
    - "康健人壽"
    - "法國巴黎人壽"
  property_insurance:
    - "國泰產險"
    - "富邦產險"
    - "新光產險"
    - "明台產險"
    - "華南產險"
    - "泰安產險"
    - "兆豐產險"
    - "第一產險"
    - "台產"
    - "旺旺友聯產險"
    - "安達產險"
    - "蘇黎世產險"
    - "美亞產險"
    - "台壽保產險"
    - "中央再保險"

# 金融機構延伸
financial_institutions:
  banks:
    - "中央銀行"
    - "台銀"
    - "土銀"
    - "合庫"
    - "第一銀"
    - "華銀"
    - "彰銀"
    - "上海商銀"
    - "兆豐銀"
    - "台企銀"
    - "中信銀"
    - "國泰世華"
    - "富邦銀"
    - "新光銀"
    - "元大銀"
    - "永豐銀"
    - "玉山銀"
    - "台新銀"
    - "聯邦銀"
    - "遠東銀"
  bancassurance:
    - "銀行保險"
    - "銀保"
    - "銀行通路"
    - "金融控股"
    - "金控"
    - "銀行理專"
    - "財富管理"

# 監管機構與政策
regulators_and_policy:
  government:
    - "金管會"
    - "保險局"
    - "金融監督管理委員會"
    - "保險安定基金"
    - "財政部"
    - "行政院"
    - "立法院"
    - "監察院"
    - "金融消保中心"
    - "保險犯防中心"
  regulations:
    - "保險法"
    - "保險業法"
    - "金融消費者保護法"
    - "個人資料保護法"
    - "洗錢防制法"
    - "RBC制度"
    - "IFRS17"
    - "償付能力"
    - "資本適足性"
    - "金檢"
    - "金融檢查"
    - "業務檢查"
    - "財務檢查"

# 科技與創新
technology_innovation:
  insurtech:
    - "保險科技"
    - "InsurTech"
    - "數位保險"
    - "網路投保"
    - "線上投保"
    - "AI理賠"
    - "機器學習"
    - "大數據"
    - "區塊鏈"
    - "物聯網"
    - "IoT保險"
    - "遠距投保"
    - "視訊投保"
  digital_transformation:
    - "數位轉型"
    - "數位化"
    - "行動投保"
    - "APP投保"
    - "電子保單"
    - "無紙化"
    - "OCR辨識"
    - "人臉辨識"
    - "語音辨識"
    - "聊天機器人"
    - "客服機器人"
    - "RPA自動化"

# 市場趨勢與議題
market_trends:
  social_trends:
    - "高齡化社會"
    - "少子化"
    - "老年人口"
    - "銀髮族"
    - "超高齡社會"
    - "人口結構"
    - "勞動人口"
    - "撫養比"
    - "出生率"
    - "死亡率"
  economic_factors:
    - "利率"
    - "央行升息"
    - "降息"
    - "通膨"
    - "通貨膨脹"
    - "經濟成長"
    - "GDP"
    - "景氣循環"
    - "匯率"
    - "股市"
    - "債市"
    - "房市"
  sustainability:
    - "ESG"
    - "永續"
    - "綠色金融"
    - "責任投資"
    - "氣候變遷"
    - "氣候風險"
    - "碳中和"
    - "淨零排放"
    - "再生能源"
    - "永續保險"

# 健康醫療相關
health_medical:
  healthcare:
    - "健保"
    - "全民健保"
    - "二代健保"
    - "醫療體系"
    - "醫院"
    - "診所"
    - "藥局"
    - "醫師"
    - "護理師"
    - "醫療品質"
    - "醫療糾紛"
    - "醫療事故"
  diseases:
    - "癌症"
    - "心臟病"
    - "腦中風"
    - "糖尿病"
    - "高血壓"
    - "腎臟病"
    - "肝病"
    - "肺病"
    - "失智症"
    - "帕金森氏症"
    - "罕見疾病"
    - "慢性病"
  mental_health:
    - "憂鬱症"
    - "精神疾病"
    - "心理健康"
    - "壓力"
    - "焦慮"
    - "自殺"
    - "心理諮商"
    - "精神科"

# 退休養老
retirement_pension:
  pension_system:
    - "勞保"
    - "勞工保險"
    - "國民年金"
    - "軍公教退撫"
    - "勞退"
    - "勞工退休金"
    - "退休金"
    - "年金改革"
    - "退休規劃"
    - "養老"
    - "老年給付"
    - "遺屬給付"
    - "失能給付"
  retirement_planning:
    - "退休理財"
    - "退休準備"
    - "退休所得"
    - "退休保障"
    - "老年經濟安全"
    - "世代正義"
    - "財務規劃"
    - "理財規劃"

# 長期照護
long_term_care:
  ltc_system:
    - "長照"
    - "長期照護"
    - "長照2.0"
    - "照護服務"
    - "居家照護"
    - "日間照護"
    - "機構照護"
    - "喘息服務"
    - "輔具服務"
    - "無障礙"
    - "失能"
    - "失智"
    - "ADL"
    - "日常生活活動"
    - "IADL"
  care_providers:
    - "看護"
    - "照服員"
    - "外籍看護"
    - "家庭照顧者"
    - "照護機構"
    - "護理之家"
    - "安養院"
    - "養護中心"
    - "日照中心"

# 意外災害
accidents_disasters:
  traffic:
    - "車禍"
    - "交通事故"
    - "機車事故"
    - "汽車事故"
    - "酒駕"
    - "闖紅燈"
    - "超速"
    - "疲勞駕駛"
    - "追撞"
    - "對撞"
  natural_disasters:
    - "地震"
    - "颱風"
    - "豪雨"
    - "淹水"
    - "土石流"
    - "山崩"
    - "海嘯"
    - "乾旱"
    - "森林火災"
    - "天然災害"
  man_made_disasters:
    - "火災"
    - "爆炸"
    - "化學災害"
    - "核災"
    - "工安意外"
    - "建築物倒塌"
    - "電梯意外"
    - "食品中毒"

# 犯罪與詐騙
crime_fraud:
  insurance_fraud:
    - "保險詐騙"
    - "詐保"
    - "假車禍"
    - "虛偽理賠"
    - "騙保"
    - "保險犯罪"
    - "偽造文書"
    - "不實申報"
  general_fraud:
    - "詐騙"
    - "詐騙集團"
    - "電話詐騙"
    - "網路詐騙"
    - "釣魚簡訊"
    - "假投資"
    - "龐氏騙局"
    - "金融詐騙"

# 消費者權益
consumer_rights:
  protection:
    - "消費者保護"
    - "消費者權益"
    - "金融消費者"
    - "申訴"
    - "爭議處理"
    - "評議"
    - "仲裁"
    - "訴訟"
    - "和解"
    - "調解"
  contract_issues:
    - "契約"
    - "保險契約"
    - "約定條款"
    - "除外條款"
    - "免責條款"
    - "告知義務"
    - "說明義務"
    - "契約解釋"
    - "不當銷售"
    - "誤導銷售"

# 投資理財
investment_finance:
  investment_products:
    - "基金"
    - "股票"
    - "債券"
    - "ETF"
    - "期貨"
    - "選擇權"
    - "結構型商品"
    - "連動債"
    - "外匯"
    - "黃金"
    - "房地產"
    - "REITs"
  financial_planning:
    - "理財"
    - "財富管理"
    - "資產配置"
    - "風險管理"
    - "投資組合"
    - "分散投資"
    - "定期定額"
    - "複利效應"
    - "通膨保護"

# 國際保險
international_insurance:
  global_trends:
    - "國際保險"
    - "全球保險"
    - "跨國保險"
    - "再保險"
    - "海外保險"
    - "境外保單"
    - "香港保單"
    - "美國保險"
    - "歐洲保險"
    - "亞洲保險"
  reinsurance:
    - "再保險"
    - "分保"
    - "自留額"
    - "巨災保險"
    - "巨災債券"
    - "天災保險"
    - "國際再保"

# 新興風險
emerging_risks:
  cyber_risks:
    - "網路風險"
    - "資安風險"
    - "駭客攻擊"
    - "個資外洩"
    - "網路犯罪"
    - "勒索軟體"
    - "資料外洩"
    - "系統中斷"
  pandemic:
    - "疫情"
    - "新冠肺炎"
    - "COVID-19"
    - "傳染病"
    - "大流行"
    - "防疫保險"
    - "疫苗"
    - "隔離"
    - "封城"

# 負面關鍵字（需要特別關注的爭議事件）
negative_keywords:
  disputes:
    - "糾紛"
    - "爭議"
    - "拒賠"
    - "不理賠"
    - "理賠困難"
    - "延遲理賠"
    - "申訴"
    - "評議"
    - "訴訟"
    - "敗訴"
    - "賠償"
  violations:
    - "違法"
    - "違規"
    - "裁罰"
    - "罰款"
    - "停業"
    - "撤照"
    - "限制業務"
    - "糾正"
    - "改善"
    - "檢查缺失"
  scandals:
    - "弊案"
    - "醜聞"
    - "內線交易"
    - "利益衝突"
    - "關係人交易"
    - "掏空"
    - "挪用"
    - "貪污"

# 排除關鍵字（過濾廣告和無關內容）
exclude_keywords:
  advertising:
    - "廣告"
    - "促銷"
    - "優惠"
    - "折扣"
    - "抽獎"
    - "贈品"
    - "好康"
    - "限時"
    - "獨家"
    - "免費"
  entertainment:
    - "代言"
    - "明星"
    - "藝人"
    - "偶像"
    - "演員"
    - "歌手"
    - "網紅"
    - "直播主"
  irrelevant:
    - "美食"
    - "旅遊"
    - "購物"
    - "時尚"
    - "娛樂"
    - "遊戲"
    - "3C產品"
    - "汽車評測"

# 搜索組合關鍵字（用於Google新聞搜索）
search_combinations:
  primary:
    - "保險"
    - "人壽保險"
    - "產險"
    - "車險"
    - "健康險"
    - "醫療險"
    - "意外險"
    - "年金險"
    - "長照險"
    - "失能險"
  secondary:
    - "金管會 保險"
    - "保險局"
    - "保險公司"
    - "保費"
    - "理賠"
    - "投保"
    - "保單"
    - "保險詐騙"
    - "保險糾紛"
    - "保險改革"
  specialized:
    - "銀行保險"
    - "保險科技"
    - "數位保險"
    - "網路投保"
    - "保險創新"
    - "ESG保險"
    - "氣候保險"
    - "網路資安險"
    - "防疫保險"
    - "疫苗保險"
  regulatory:
    - "保險法修正"
    - "保險業法"
    - "RBC制度"
    - "IFRS17"
    - "償付能力"
    - "保險監理"
    - "金融檢查"
    - "保險罰款"
    - "保險違規"
    - "保險裁罰"
