# 保險新聞關鍵字配置
# Insurance News Keywords Configuration

# 保險類型關鍵字
insurance_types:
  - "壽險"
  - "產險" 
  - "車險"
  - "健康險"
  - "意外險"
  - "旅平險"
  - "醫療險"
  - "癌症險"
  - "失能險"
  - "年金險"
  - "投資型保單"
  - "外幣保單"

# 保險公司關鍵字
insurance_companies:
  - "國泰人壽"
  - "富邦人壽"
  - "新光人壽"
  - "南山人壽"
  - "中國人壽"
  - "台灣人壽"
  - "全球人壽"
  - "三商美邦"
  - "宏泰人壽"
  - "遠雄人壽"
  - "國泰產險"
  - "富邦產險"
  - "新光產險"
  - "明台產險"
  - "華南產險"

# 監管機構關鍵字
regulators:
  - "金管會"
  - "保險局"
  - "金融監督管理委員會"
  - "保險安定基金"
  - "財政部"

# 保險專業術語
insurance_terms:
  - "保費"
  - "保額"
  - "理賠"
  - "保單"
  - "受益人"
  - "要保人"
  - "被保險人"
  - "保險金"
  - "給付"
  - "免賠額"
  - "等待期"
  - "寬限期"
  - "復效"
  - "解約"
  - "減額繳清"
  - "保單貸款"
  - "紅利"
  - "分紅"

# 市場趨勢關鍵字
market_trends:
  - "數位保險"
  - "網路投保"
  - "保險科技"
  - "InsurTech"
  - "區塊鏈保險"
  - "AI理賠"
  - "大數據分析"
  - "ESG永續"
  - "氣候風險"
  - "高齡化社會"
  - "少子化"
  - "長照險"

# 法規政策關鍵字
regulations:
  - "保險法"
  - "保險業法"
  - "金融消費者保護法"
  - "個人資料保護法"
  - "洗錢防制法"
  - "RBC制度"
  - "IFRS17"
  - "償付能力"
  - "資本適足性"

# 負面關鍵字（需要特別關注）
negative_keywords:
  - "詐騙"
  - "糾紛"
  - "申訴"
  - "拒賠"
  - "爭議"
  - "罰款"
  - "違法"
  - "裁罰"
  - "停業"
  - "撤照"

# 排除關鍵字（過濾雜訊）
exclude_keywords:
  - "廣告"
  - "促銷"
  - "優惠"
  - "抽獎"
  - "贈品"
  - "代言"
  - "明星"
